# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1X8GtxIhehP45P6tpp8VhveI9FSSElxHY
"""

import numpy as np
from flask import Flask, request, render_template
import pickle
import os

import numpy as np
from flask import Flask, request, render_template
import pickle

app = Flask(__name__)
model = pickle.load(open('model1.pkl', 'rb'))  # Load trained model

@app.route('/')
def home():
    return render_template('index.html')

@app.route('/predict', methods=['POST'])
def predict():
    '''
    For rendering results on HTML GUI
    '''
    hours_studied = float(request.form['hours_studied'])  # Get the input value from the form
    # Prepare the input data for prediction
    final_features = np.array([[hours_studied]])

    prediction = model.predict(final_features)

    output = round(prediction[0], 2)

    return render_template('index.html', prediction_text='Predicted Score for {} Hours of Studying: {}'.format(hours_studied, output))

if __name__ == "__main__":
    app.run(debug=True,port=int(os.environ.get("PORT", 5000)))