# -*- coding: utf-8 -*-
"""dummymodel2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uUPuB_0f_mDmlcB-9rVaY6g2P5bx947i

#DUMMY MODEL
> Indented block
"""

import pandas as pd
import numpy as np
import pickle
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

df = pd.read_csv("student_scores.csv")

X = df['Hours']
Y = df['Scores']

# data spliting into train and test

X_train,X_test,Y_train,Y_test  = train_test_split(X,Y,test_size =0.2, random_state = 10)

len(X_train)
len(X_test)
len(Y_train)
len(Y_test)

model1 = LinearRegression()

X_train = np.array(X_train).reshape(-1, 1)
model1.fit(X_train, Y_train)

X_test = np.array(X_test).reshape(-1,1)
test_result = model1.predict(X_test)

#X_test = np.array(X_test).reshape(-1)
#df_result = pd.DataFrame({'X_test':X_test,'Y_test':Y_test,'Y-predicted':test_result})
#df_result

pickle.dump(model1,open('model1.pkl','wb'))

# Load the trained model
loaded_model = pickle.load(open('model1.pkl', 'rb'))

# Prepare the input data for prediction (1 hour of studying)
hours_studied = np.array([[2]])

# Make a prediction
predicted_score = loaded_model.predict(hours_studied)

# Print the predicted score
print(f"Predicted Score for 2 Hours of Studying: {predicted_score[0]}")